INSERT INTO analysis_session (
    session_id,
    user_id,
    title,
    user_goal,
    status,
    scene_id,
    current_task_id,
    latest_result_bundle_id,
    current_required_user_action_json,
    session_summary_json,
    created_at,
    updated_at
)
VALUES (
    'sess_live_urban_cooling',
    1,
    'Urban Cooling for Heat Mitigation',
    'Start an urban cooling analysis for heat mitigation.',
    'RUNNING',
    'scene-urban-cooling-for-heat-mitigation',
    'task_live_urban_cooling',
    NULL,
    NULL,
    jsonb_build_object(
        'task_id', 'task_live_urban_cooling',
        'status', 'RUNNING',
        'user_goal', 'Start an urban cooling analysis for heat mitigation.',
        'latest_result_bundle_id', NULL
    )::text,
    TIMESTAMPTZ '2026-04-14T02:00:00Z',
    TIMESTAMPTZ '2026-04-14T02:00:00Z'
);

INSERT INTO task_state (
    task_id,
    session_id,
    user_id,
    current_state,
    state_version,
    user_query,
    pass1_result_json,
    goal_parse_json,
    skill_route_json,
    passb_result_json,
    slot_bindings_summary_json,
    args_draft_summary_json,
    validation_summary_json,
    input_chain_status,
    job_id,
    pass2_result_json,
    result_object_summary_json,
    result_bundle_summary_json,
    final_explanation_summary_json,
    last_failure_summary_json,
    waiting_context_json,
    waiting_reason_type,
    resume_payload_json,
    resume_txn_json,
    resume_attempt_count,
    active_attempt_no,
    active_manifest_id,
    active_manifest_version,
    planning_revision,
    checkpoint_version,
    inventory_version,
    cognition_verdict,
    corruption_reason,
    latest_result_bundle_id,
    latest_workspace_id,
    corrupted_since,
    waiting_since,
    created_at,
    updated_at
)
VALUES (
    'task_live_urban_cooling',
    'sess_live_urban_cooling',
    1,
    'CREATED',
    0,
    'Start an urban cooling analysis for heat mitigation.',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1,
    NULL,
    NULL,
    0,
    0,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    TIMESTAMPTZ '2026-04-14T02:00:00Z',
    TIMESTAMPTZ '2026-04-14T02:00:00Z'
);
