INSERT INTO analysis_session (
    session_id,
    user_id,
    title,
    user_goal,
    status,
    scene_id,
    current_task_id,
    latest_result_bundle_id,
    current_required_user_action_json,
    session_summary_json,
    created_at,
    updated_at
)
VALUES (
    'sess_live_water_yield',
    1,
    'Water Yield for Gura Subwatersheds',
    'Identify which subwatersheds contribute the most annual water yield and summarize what the pattern implies for watershed management.',
    'RUNNING',
    'scene-water-yield-for-gura-subwatersheds',
    'task_live_water_yield',
    NULL,
    NULL,
    jsonb_build_object(
        'task_id', 'task_live_water_yield',
        'status', 'RUNNING',
        'user_goal', 'Identify which subwatersheds contribute the most annual water yield and summarize what the pattern implies for watershed management.',
        'latest_result_bundle_id', NULL
    )::text,
    TIMESTAMPTZ '2026-04-14T08:00:00Z',
    TIMESTAMPTZ '2026-04-14T08:00:00Z'
)
ON CONFLICT (session_id) DO NOTHING;

INSERT INTO task_state (
    task_id,
    session_id,
    user_id,
    current_state,
    state_version,
    user_query,
    pass1_result_json,
    goal_parse_json,
    skill_route_json,
    passb_result_json,
    slot_bindings_summary_json,
    args_draft_summary_json,
    validation_summary_json,
    input_chain_status,
    job_id,
    pass2_result_json,
    result_object_summary_json,
    result_bundle_summary_json,
    final_explanation_summary_json,
    last_failure_summary_json,
    waiting_context_json,
    waiting_reason_type,
    resume_payload_json,
    resume_txn_json,
    resume_attempt_count,
    active_attempt_no,
    active_manifest_id,
    active_manifest_version,
    planning_revision,
    checkpoint_version,
    inventory_version,
    cognition_verdict,
    corruption_reason,
    latest_result_bundle_id,
    latest_workspace_id,
    corrupted_since,
    waiting_since,
    created_at,
    updated_at
)
VALUES
(
    'task_live_water_yield',
    'sess_live_water_yield',
    1,
    'CREATED',
    0,
    'Identify which subwatersheds contribute the most annual water yield and summarize what the pattern implies for watershed management.',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1,
    NULL,
    NULL,
    0,
    0,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    TIMESTAMPTZ '2026-04-14T08:00:00Z',
    TIMESTAMPTZ '2026-04-14T08:00:00Z'
),
(
    'task_demo_water_yield',
    'sess_live_water_yield',
    1,
    'SUCCEEDED',
    18,
    'Identify which subwatersheds contribute the most annual water yield and summarize what the pattern implies for watershed management.',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'job_demo_water_yield_1',
    NULL,
    NULL,
    jsonb_build_object(
        'result_id', 'rb_demo_water_yield_gura_2024',
        'summary', 'Annual water yield outputs are ready for the Gura watershed and subwatersheds.',
        'main_output_count', 2,
        'main_outputs', jsonb_build_array('gura_water_yield_subwatersheds.gpkg', 'gura_water_yield_supply_summary.csv'),
        'primary_outputs', jsonb_build_array('gura_water_yield_subwatersheds.gpkg'),
        'audit_artifacts', jsonb_build_array('water_yield_method_note.md'),
        'created_at', '2026-04-14T08:12:00Z'
    )::text,
    jsonb_build_object(
        'title', 'Annual water yield contribution patterns are ready',
        'highlight_count', 3,
        'generated_at', '2026-04-14T08:12:30Z',
        'available', true
    )::text,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    1,
    NULL,
    NULL,
    0,
    0,
    0,
    'PASS',
    NULL,
    'rb_demo_water_yield_gura_2024',
    'ws_demo_water_yield_1',
    NULL,
    NULL,
    TIMESTAMPTZ '2026-04-14T08:00:00Z',
    TIMESTAMPTZ '2026-04-14T08:12:30Z'
)
ON CONFLICT (task_id) DO NOTHING;

INSERT INTO job_record (
    job_id,
    task_id,
    attempt_no,
    job_state,
    workspace_id,
    provider_key,
    capability_key,
    runtime_profile,
    result_bundle_json,
    final_explanation_json,
    failure_summary_json,
    workspace_summary_json,
    artifact_catalog_json,
    accepted_at,
    started_at,
    finished_at,
    last_heartbeat_at,
    created_at,
    updated_at
)
VALUES (
    'job_demo_water_yield_1',
    'task_demo_water_yield',
    1,
    'SUCCEEDED',
    'ws_demo_water_yield_1',
    'planning-pass1-invest-local',
    'water_yield',
    'docker-invest-real',
    jsonb_build_object(
        'result_id', 'rb_demo_water_yield_gura_2024',
        'task_id', 'task_demo_water_yield',
        'job_id', 'job_demo_water_yield_1',
        'summary', 'Annual water yield outputs are ready for the Gura watershed and subwatersheds.',
        'metrics', jsonb_build_object(
            'priority_subwatersheds', 4,
            'main_output_count', 2
        ),
        'created_at', '2026-04-14T08:12:00Z'
    )::text,
    jsonb_build_object(
        'title', 'Water yield contribution patterns and management implications are ready',
        'narrative', 'The strongest annual water yield contribution is concentrated in a subset of Gura subwatersheds, especially the upper catchments where precipitation input is stronger and land-cover conditions support higher runoff and supply generation. These subwatersheds matter most because they contribute disproportionately to downstream water availability relative to the rest of the study area. From a management perspective, this suggests prioritizing protection and monitoring in the high-yield catchments, while using the lower-yield subwatersheds to flag areas where land-use pressure or vegetation change could reduce future supply stability.',
        'generated_at', '2026-04-14T08:12:30Z'
    )::text,
    NULL,
    jsonb_build_object(
        'workspace_id', 'ws_demo_water_yield_1',
        'workspace_output_path', 'runtime/workspaces/ws_demo_water_yield_1/output',
        'archive_path', NULL,
        'cleanup_completed', false,
        'archive_completed', false
    )::text,
    jsonb_build_object(
        'primary_outputs', jsonb_build_array(
            jsonb_build_object(
                'artifact_id', 'artifact_demo_water_yield_subwatersheds',
                'artifact_role', 'PRIMARY_OUTPUT',
                'logical_name', 'subwatershed_water_yield',
                'relative_path', 'outputs/gura_water_yield_subwatersheds.gpkg',
                'content_type', 'application/geopackage+sqlite3',
                'size_bytes', 24576,
                'sha256', 'demo-water-yield-subwatersheds',
                'created_at', '2026-04-14T08:12:00Z'
            )
        ),
        'intermediate_outputs', jsonb_build_array(),
        'audit_artifacts', jsonb_build_array(
            jsonb_build_object(
                'artifact_id', 'artifact_demo_water_yield_note',
                'artifact_role', 'AUDIT',
                'logical_name', 'method_note',
                'relative_path', 'artifacts/water_yield_method_note.md',
                'content_type', 'text/markdown',
                'size_bytes', 1024,
                'sha256', 'demo-water-yield-note',
                'created_at', '2026-04-14T08:12:20Z'
            )
        ),
        'derived_outputs', jsonb_build_array()
    )::text,
    TIMESTAMPTZ '2026-04-14T08:02:00Z',
    TIMESTAMPTZ '2026-04-14T08:03:00Z',
    TIMESTAMPTZ '2026-04-14T08:12:00Z',
    TIMESTAMPTZ '2026-04-14T08:12:00Z',
    TIMESTAMPTZ '2026-04-14T08:02:00Z',
    TIMESTAMPTZ '2026-04-14T08:12:00Z'
)
ON CONFLICT (job_id) DO NOTHING;
